# 项目相关配置
ruoyi:
  # 实例演示开关
  demoEnabled: false
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /usr/java/uploadPath

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /gcxw
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  level:
    com.ruoyi: error
    org.springframework: error


# Spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
          url: jdbc:mysql://127.0.0.1:3306/gcxw?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
          username: root
          password: root
  devtools:
    restart:
      # 热部署开关
      enabled: false